server:
  port: 8082  # 图片服务端口

spring:
  application:
    name: VogFashion-Image
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: ${vision.datasource.driver-class-name}
    url: ${vision.datasource.image.url}
    username: ${vision.datasource.image.username}
    password: ${vision.datasource.image.password}


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html # Swagger UI的路径（Knife4j增强后主要用doc.html）
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wtu.controller # 扫描所有 Controller

  cloud:
    openfeign:
      okhttp:
        enabled: true


logging:
  level:
    com:
      wtu:
        mapper: debug
        service: info
        controller: info
wtu:
  alioss:
    endpoint: ${vision.alioss.endpoint}
    access-key-id: ${vision.alioss.access-key-id}
    access-key-secret: ${vision.alioss.access-key-secret}
    bucket-name: ${vision.alioss.bucket-name}
